### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by mauphung** [rinvex/laravel-menus#24]
When publish rinvex-menus-views, it cannot locate publishable resources.
Would you please help me to fix this error?
Thanks

php artisan vendor:publish --tag="rinvex-menus-views"
Unable to locate publishable resources.
Publishing complete.

**Comment by Omranic** [comment]
This issue has been fixed in recent release v4.x please test and let me know if you still have any other issues or questions. Feel free to re-open this for more discussion.
