### ISSUE TITLE
[Bug] View Presenter MenuGenerator::render() return type issue

### ISSUE THREAD

**Issue by s207152** [rinvex/laravel-menus#4]
Once I tried to render through view, I got the following error.

```
Type error: Return value of Rinvex\Menus\Models\MenuGenerator::render() must be of the type string, object returned
```

The cause is that ```MenuGenerator::renderView()``` is returning ```Illuminate\Contracts\View\View```.

**Comment by Omranic** [comment]
PR Merged! Thank you @s207152 :)
