### ISSUE TITLE
 Trait 'Rinvex\Support\Traits\ConsoleTools' not found

### ISSUE THREAD

**Issue by ksorbo** [rinvex/laravel-menus#8]
I get this error when attempting to install:
Using Laravel 5.8

In MenusServiceProvider.php line 13:

  Trait 'Rinvex\Support\Traits\ConsoleTools' not found

PHP Fatal error:  Trait 'Rinvex\Support\Traits\ConsoleTools' not found in C:\Users\keith\PHPStormProjects\disciple\vendor\rinvex\laravel-menus\src\Providers\MenusServiceProvider.php on line 13
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by Omranic** [comment]
Thank you, fixed in 0e0b397c05af014b1e6326d78e2c1aaf45b63d9c
